In [22]:
import random
from random import sample, seed

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf

from sklearn import linear_model
from sklearn.datasets import load_boston
from sklearn.datasets import make_classification
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.impute import SimpleImputer 

%matplotlib inline
%load_ext autoreload
%autoreload 2

np.set_printoptions(precision=5, suppress=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
boston = load_boston()
dataset = pd.DataFrame(boston.data, columns=boston.feature_names)
dataset['target'] = boston.target
dataset

observations = len(dataset)
variables = dataset.columns[:-1]
X = dataset.iloc[:, :-1]
y = dataset['target'].values

In [2]:
example = np.array([1, 2, np.nan, 4, 5])
example

array([ 1.,  2., nan,  4.,  5.])

In [3]:
np.isnan(example)

array([False, False,  True, False, False])

In [4]:
np.nan_to_num(example)

array([1., 2., 0., 4., 5.])

In [9]:
missing = np.isnan(example)
replaceing_value = np.mean(example[~missing])
example[missing] = replaceing_value
example

array([1., 2., 3., 4., 5.])

In [17]:
seed(19)
Xm = X.copy()
missing = sample(range(len(y)), len(y) // 4)
Xm.iloc[missing, 5] = np.nan

In [19]:
print("Header of Xm[:, 5]: {}".format(Xm.iloc[:10, 5]))

Header of Xm[:, 5]: 0    6.575
1      NaN
2    7.185
3      NaN
4    7.147
5    6.430
6    6.012
7    6.172
8      NaN
9    6.004
Name: RM, dtype: float64


In [39]:
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(Xm)
impute.transform(X)[0][:10]

array([  0.00632,  18.     ,   2.31   ,   0.     ,   0.538  ,   6.575  ,
        65.2    ,   4.09   ,   1.     , 296.     ])